# Generated by Django 3.0.7 on 2024-01-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
