# Generated by Django 3.0.7 on 2024-01-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_deposited',
            field=models.BooleanField(default=False),
        ),
    ]
