# Generated by Django 3.0.7 on 2024-01-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
        migrations.AddField(
            model_name='deposit',
            name='car_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deposit',
            name='car_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deposit',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deposit',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deposit',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deposit',
            name='user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
