# Generated by Django 3.0.7 on 2024-01-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_auto_20240108_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='amount',
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_amount',
            field=models.FloatField(default=0),
        ),
    ]
